
<?php

use FWAP\Library\Timestamp;
use FWAP\Library\Session;
?>
<!-- { col-2 | col-3 | col-4 } -->

<section class="content">
    <div class="col-lg-4 pull-right">

        <div class="row">

            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor libero ducimus distinctio nobis maxime vero natus aperiam necessitatibus sit explicabo saepe veniam, accusamus nihil inventore minima quae eveniet modi quasi?


            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam tempora possimus cum labore quia aperiam, voluptatum, placeat facilis earum unde quidem doloremque quasi fuga quibusdam, dolorum neque quas. Facilis, natus.

        </div>
    </div>
</section>





