<?php

/**
 *
 * knut7 Framework (http://framework.artphoweb.com/)
 * knut7 FW(tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2016.  knut7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.0
 */
use FWAP\Library\Form;
// use FWAP\Library\Cookie;
use FWAP\Helpers\Hook;
?>


<div class="container top">
    <section>

        <div class="row">

            <!-- Jumbotron -->
            <div class="jumbotron">
                <div class="container text-center">
                    <h1>Welcome knut7 Framework</h1>

                    <p>Hello, welcome from the welcome Controller! </p>
                    <div class="btn-group">
                        <a href="https://www.facebook.com/knut7-Framework" class="btn btn-lg btn-primary">FACEBOOK</a>
                        <a href="https://github.com/knut7-framework/knut7-framework" class="btn btn-lg btn-info">CONTRIBUTE</a>
                        <a href="https://github.com/knut7-framework/knut7-framework/archive/master.zip" class="btn btn-lg btn-danger">DOWNLOAD</a>
                    </div>
                </div><!-- End Container -->

            </div><!-- End Jumbotron -->

            <div class="row">
                <div class="col-lg-4">
                    <div class="panel panel-default text-center">
                        <div class="panel-body">
                            <span class="glyphicon glyphicon-star"></span>
                            <h3>What is the knut7?</h3>
                            <p class="panel text-justify">The knut7 is a framework created and maintained by Artphoweb to facilitate the rapid development of FWAPs for any developer experienced or not!</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="panel panel-default text-center">
                        <div class="panel-body">
                            <span class="glyphicon glyphicon-ok"></span>
                            <h3>Why Use!</h3>
                            <p class="panel text-justify">It is modular. Everything goes in the folder module. The great benefit in knut7 is because it be fully modular. You can install a module in MVC by the composer or even remove it without that there complications!!. The modules are fully substitutable!</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="panel panel-default text-center">
                        <div class="panel-body">
                            <span class="glyphicon glyphicon-play-circle"></span>
                            <h3>News</h3>
                            <p class="panel text-justify"></p>
                        </div>
                    </div>
                </div>
                <div class="jumbotron-hr"></div>
            </div><!-- End Row --></section>
            <?php foreach ($this->public as $key => $value) : ?>

                <div class="col-lg-4">
                    <div class="panel panel-default text-center">
                        <div class="panel-body">
                            <span class="glyphicon glyphicon-ok"></span>
                            <h4><?php echo $value['title']; ?></h4>
                            <footer><?php echo $value['post_date']; ?></footer>
                            <p><?php echo $value['excerpt']; ?></p>
                        </div>
                        <div class="group">
                            <a href="Article/art_pre_post/<?php echo $value['id_article']; ?>" class="btn btn-danger"> ler mais </a>
                        </div>
                    </div> <!-- panel panel-default text-center -->
                </div> <!-- col-lg-4 -->
            <?php endforeach; ?>
        </div><!-- End Row -->
    </section>
</div>

<!-- Call to action -->
<section>
    <div class="well">
        <div class="container text-center">
            <h3>Sobrescreve para mais informações</h3>
            <p>Coloca aqui seu nome e email</p>

            <?php
            echo Form::open(['action' => ' ', 'class' => 'form-inline']);
            ?>
            <div class="form-group">
                <label for="subscription">Sobrescreve</label>
                <?php
                echo Form::input(['type' => 'nome', 'class' => 'form-control', 'id' => 'subscription', 'placeholder' => 'Seu Nome']);
                ?>
            </div>
            <div class="form-group">
                <label for="email">Endereço de Email</label>
                <?php
                echo Form::input(['type' => 'email', 'class' => 'form-control', 'id' => 'subscription', 'placeholder' => 'Email']);
                ?>
            </div>
            <?php
            echo Form::button(['type' => 'submit', 'class' => 'btn btn-danger', 'id' => 'subscription', 'value' => 'Sobrescreve']);
            ?>
            <hr>
            <?php
            echo Form::close();
            ?>
        </div>
    </div>
</section><!-- Call to action -->






