#!usr/bin/env php
<?php
/**
 * knut7 - a simple framework for PHP Developers
 *
 * @author   izni burak demirtaş (@izniburak) <izniburak@gmail.com>
 * @url      <https://github.com/izniburak/knut7>
 * @license  The MIT License (MIT) - <http://opensource.org/licenses/MIT>
 */

require __DIR__.'/vendor/autoload.php';

use Ballybran\Kernel\Application;
use App\Console\Application as ConsoleApplication;
use Symfony\Component\Console\Application as SymfonyApplication;


$app = new Application;


define('KNUT_VERSION', $app->version());
define('APP_ENV', strtolower(config('app.env')));

$console = new ConsoleApplication(new SymfonyApplication("      _ __  _   _ _ __
     | '_ \| | | | '__|
     | | | | |_| | |
     |_| |_|\__,_|_| v" . KNUT_VERSION . "
  Knut7 - PHP Framework"), $app);
$console->run();
