<?php

/**
 *
 * knut7 Framework (http://framework.artphoweb.com/)
 * knut7 FW(tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2016.  knut7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.0
 */
use FWAP\Helpers\Form;
?>
<div class="well">
    <div class="container text-center">

        <?php
        echo Form::open(['method' => 'post', 'action' => URL . 'SearchUser/getSearch', 'name' => 'signin', 'class' => 'form-inline', 'style' => 'width: 500px;']);
        ?>
        <div class="form-group">
            <label for="subscription">Procurar</label>
            <!-- <input type="text" class="form-control" id="subscription" placeholder=" Seu Nome"> -->
            <?php
            echo Form::input(['type' => 'text', 'name' => 'busca', 'class' => 'form-control']);
            ?>

        </div>
        <?php
        echo Form::button(['type' => 'submit', 'class' => 'btn btn-danger', 'value' => 'Buscar']);
        ?>
        <hr>
        <?php
        echo Form::close();
        ?>

    </div>
</div><!-- End Well -->
</section><!-- Call to action -->

<script>

    function res() {
        alert(1);
    }

</script>
