<?php
/**
 *
 * knut7 Framework (http://framework.artphoweb.com/)
 * knut7 FW(tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2016.  knut7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.0
 */
/**
 * Date: 2016/02/14
 * Time: 11:13 AM
 */
?>


<section class="content-3 col-3">
    <div class="container">
        <div class="row">
            <br/><br/>     
            <div class="page-header breadcrumb" id="features">
                <?php foreach ($this->categoryByNameTitle as $key => $values) : ?>

                    <strong><a href="<?php echo URL; ?>categorias">CATEGORIAS</a></strong> /<i> <?php echo $values['name']; ?></i>
                <?php endforeach; ?>
            </div>
            <?php foreach ($this->category as $key => $value) :
                ?>

                <div class="col-lg-4">
                    <div class="panel panel-default text-center">
                        <div class="panel-body">
                            <span class="glyphicon glyphicon-ok"></span>
                            <footer><h4><?php echo $value['title']; ?></h4></footer>
                            <p><?php echo $value['excerpt']; ?></p>
                        </div>
                        <div class="group">
                            <a href="<?php echo URL; ?>Article/art_pre_post/<?php echo $value['id_article']; ?>" class="btn btn-danger">Ler Mais</a>
                        </div>
                    </div> <!-- panel panel-default text-center -->
                </div> <!-- col-lg-4 -->
            <?php endforeach; ?>
        </div><!-- End Row -->
    </div>
</section>
