

<div class="container">
    <section>
        <div class="page-header text-center" id="contact ">
            <h2>POSTAR FAQ<small></small></h2>
        </div> <!-- End Page Header -->

        <div id="content" class="col-sm-9">
            <div class="well">
                <form method="post" action="<?php echo URL ?>Faq/insertFaq" style="margin-left:30%;">
                    <div class="form-group">
                        <input type="text" name="quest" class="form-control" placeholder="Pergunta">

                    </div>
                    <div class="form-group">

                        <textarea type="text" name="respo" id="elm1" class="form-control" placeholder="Resposta"></textarea>

                    </div>
                    <button class="btn btn-lg btn-primary btn-block btn-danger" type="submit"> PUBLICAR </button>


                </form>
            </div>
        </div>
    </section>

</div>
