<h1 class="text-center" style="margin-top: 25%; font-family: Arial, Helvetica, sans-serif;">Welcome To KnuT 7 !!!</h1>
            <h4 class="text-center" style="margin-top: 1%; font-family:Arial;"><a href="https://github.com/knut7/knut7/wiki/">DOCUMENTATION</a>  |  <a href="https://github.com/knut7">CONTRIBUTING</a>  |  <a
                    href="https://github.com/knut7/framework/releases/tag/1.0.4">DOWNLOAD</a></h4>
<h4 class="text-center" style="margin-top: 22%; font-family:Arial;">Version <?php echo VERSION; ?></h4>

