
<?php


?>


<div class="container">
    <section>

        <div class="page-header text-center btn-default">

        </div>
        <div class="pull-right">
            <?php
            use FWAP\Library\Form;

            echo Form::button(['type' => 'submit', 'class' => 'btn  btn-info glyphicon glyphicon-save', 'id' => 'send_request']);
            ?>

            <a href="<?php echo URL; ?>Dashboard/customers" data-toggle="tooltip" title class="btn btn-info" data-original-title="Add Noew" ><i class="glyphicon  glyphicon-repeat"></i></a>
        </div>
        <h2>Register New User</h2>


        <?php
        echo Form::open(['method' => 'post', 'action' => URL . 'User/signUp', 'files' => 'enctype=multipart/form-data', 'name' => 'signUp', 'class' => 'form-signin', 'style' => 'margin-left:30%;']);
        ?>

        <div class="form-group">
            <label class="control-label" for="input-firstname">Nome</label>
            <?php
            echo Form::input(['type' => 'text', 'name' => 'firstname', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Nome Completo']);
            ?>
        </div>

        <div class="form-group">
            <label class="control-label" for="input-firstname">Nome</label>
            <?php
            echo Form::input(['type' => 'text', 'name' => 'lastname', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Nome Completo']);
            ?>
        </div>
        <div class="form-group">
            <label class="control-label" for="input-firstname">Username</label>

            <?php
            echo Form::input(['type' => 'text', 'name' => 'username', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'user name']);
            ?>

        </div>
        <div class="form-group">
            <label class="control-label" for="input-firstname">Email</label>

            <?php
            echo Form::input(['type' => 'email', 'name' => 'email', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'email']);
            ?>

        </div>
        <div class="form-group">
            <label class="control-label" for="input-firstname">Password</label>

            <?php
            echo Form::input(['type' => 'password', 'name' => 'password', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Password']);
            ?>
        </div>

        <?php
        echo Form::close();
        ?>


    </section>
</div>

<script>
    $(function () {

        $('#send_request').click(function (e) {
            e.preventDefault();
            signUp();
        });

    });

    function signUp() {
        var firstname = $('form[name=signUp] input[name=firstname]')[0].value;
        var lastname = $('form[name=signUp] input[name=lastname]')[0].value;
        var username = $('form[name=signUp] input[name=username]')[0].value;
        var email = $('form[name=signUp] input[name=email]')[0].value;
        var password = $('form[name=signUp] input[name=password]')[0].value;

        $.ajax({
            type: 'POST',
            url: '<?php echo URL; ?>User/signUp',
            data: {firstname: firstname, lastname: lastname, username: username, email: email, password: password}
        }).done(function (resposta) {
            if (resposta) {
                alert(" inserido");
                document.location = '<?php echo URL; ?>DataInfo';

            } else {
                alert("nada inserido");
            }
        });

    }
</script>
