
<?php
/**
 * Created by PhpStorm.
 * User: artphotografie
 * Date: 2016/02/14
 * Time: 12:39 PM
 */


/**
 *
 * Tinymce styple
 *
 * */
use \FWAP\Helpers\Copyright\Copyright;
use FWAP\Helpers\System;

?>

<script src="<?php echo URL; ?>Public/bootstrap/js/jquery-3.2.1.js"></script>
<script src="<?php echo URL; ?>Public/bootstrap-4/js/bootstrap.min.js"></script>
<script src="<?php echo URL; ?>Public/bootstrap-4/js/bootstrap.js"></script>
<br>
<footer class="panel-footer modal-footer bg-inverse text-white ">
    <?php echo  Copyright::copyright(2015, 'APWEB FRAMWORK') . '<br>';
    echo System::time_start() . ' --' . System::getOS(); ?></footer>
</body>
</html>

