<?php

/**
 *
 * knut7 Framework (http://framework.artphoweb.com/)
 * knut7 FW(tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2016.  knut7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.0
 */
use FWAP\Helpers\Form;
?>

<section>
    <div class="container col-sm-9">

        <div class="pull-right">
            <a href="<?php echo URL; ?>Customers/add" data-toggle="tooltip" title class="btn btn-info" data-original-title="Add Noew" ><i class="glyphicon glyphicon-plus"></i></a>
        </div>

        <?php require_once 'column_left.phtml'; ?>


        <table class="col-lg-4 table table-bordered table-responsive pull-right">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>User Name</th>
                    <th>Email</th>
                    <th>Privilegio</th>
                    <th>Satus</th>
                    <th>Action</th>
                    <th>editar</th>
                    <th>deletar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->user as $key => $value) { ?>
                    <tr>
                        <td><?php echo $value['firstname'] . "\n" . $value['lastname']; ?></td>
                        <td><?php echo $value['username']; ?></td>
                        <td><?php echo $value['email']; ?></td>
                        <td><?php echo $value['role']; ?></td>
                        <td> on</td>

                        <td><a class="btn btn-info glyphicon glyphicon-apple" href="#"></a>
                        </td>
                        <td> <a class="btn btn-danger glyphicon glyphicon-edit" id="edita" href="<?php echo URL; ?>Customers/edit/<?php echo $value['id']; ?>"></a></td>
                        <td><a class="btn btn-danger" href="<?php echo URL ?>Customers/deletes/<?php echo $value['id']; ?>"><i class="glyphicon glyphicon-trash "></i></td>



                    </tr>
                <?php } ?>

            </tbody>
        </table>
    </div>


</div><!-- End Well -->
</section><!-- Call to action -->

<p>Not loaded yet.</p>




