<!-- Call to action -->
<section class="col-lg-3">
    <div class="well">
        <div class="container">
            <h3>Dashboard</h3>
            <nav>
                <ul>
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="<?php echo URL; ?>/article/Publish">Postar Artigo</a></li>
                    <li><a id="" href="<?php echo URL; ?>/Dashboard/customers">Customers</a></li>
                    <li class=""><a href="<?php echo URL; ?>account/getImage">CARREGA FOTOS</a> </li>
                    <li class=""><a href="<?php echo URL; ?>article/Publish">PUBLICAR</a> </li>
                    <li class=""><a href="<?php echo URL; ?>Categorias/createCategory">PUBLICAR CATEGORIA</a> </li>
                    <li class=""><a href="<?php echo URL; ?>Faq/insertFaq">PFAQ</a> </li>
                    <li class=""><a href="<?php echo URL; ?>uploads">UPLOADS</a> </li>
                    </li>
                </ul>
            </nav>

        </div>


    </div><!-- End Well -->
</section><!-- Call to action -->
