

<?php
/**
 * Created by PhpStorm.
 * User: artphotografie
 * Date: 2016/02/14
 * Time: 12:39 PM
 */
?>

<?php

/**
 *
 * Tinymce styple
 *
 * */
use FWAP\Helpers\Assets;
use \FWAP\Library\Copyright\Copyright;
?>

<script src="<?php echo URL; ?>Public/bootstrap/jQuery.js"></script>
<script src="<?php echo URL; ?>Public/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo URL; ?>Public/tinymce/tinymce.min.js"></script>
<script src="<?php echo URL; ?>Public/tinymce/jquery.tinymce.min.js"></script>
<script src="<?php echo URL; ?>Public/Js/tinymce.init.js"></script>
<script src="<?php echo URL; ?>Public/Js/jquery.validate.js"></script>
<script src="<?php echo URL; ?>Public/js/style.js"></script>
<script src="<?php echo DIR_FILE; ?>Public/js/jQuery.js"></script>

<script src="<?php echo DIR_FILE; ?>Public/js/logout.js"></script>

<br/><br/>
<footer class="footer panel-footer text-center ">
    <?php echo  \FWAP\Helpers\Copyright\Copyright::copyright(2015, 'knut7 FRAMWORK'); ?>
</footer>
</body>
</html>

